#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Hikaru Yoshida
# SPDX-License-Identifier: BSD-3-Clause

import sys

gyo = [list(map(float, input().split())) for l in range(3)]

def gya(gyo):
    x = (gyo[0][0]*gyo[1][1]*gyo[2][2] + 
         gyo[0][1]*gyo[1][2]*gyo[2][0] + 
         gyo[0][2]*gyo[1][0]*gyo[2][1] - 
         gyo[0][2]*gyo[1][1]*gyo[2][0] - 
         gyo[0][1]*gyo[1][0]*gyo[2][2] - 
         gyo[0][0]*gyo[1][2]*gyo[2][1])

    if x == 0:
        return 1
    else:
        y = 1/x 

        a= y * (gyo[1][1]*gyo[2][2]-gyo[1][2]*gyo[2][1])
        b= -y * (gyo[0][1]*gyo[2][2]-gyo[0][2]*gyo[2][1])
        c= y * (gyo[0][1]*gyo[1][2]-gyo[0][2]*gyo[1][1])
        d= -y * (gyo[1][0]*gyo[2][2]-gyo[1][2]*gyo[2][0])
        e= y * (gyo[0][0]*gyo[2][2]-gyo[0][2]*gyo[2][0])
        f= -y * (gyo[0][0]*gyo[1][2]-gyo[0][2]*gyo[1][0])
        g= y * (gyo[1][0]*gyo[2][1]-gyo[1][1]*gyo[2][0])
        h= -y * (gyo[0][0]*gyo[2][1]-gyo[0][1]*gyo[2][0])
        i= y * (gyo[0][0]*gyo[1][1]-gyo[0][1]*gyo[1][0])
    
        return [[a,b,c],[d,e,f],[g,h,i]]



z = gya(gyo)
if z == 1:
    print("ERROR")

else:
    print(f"{z[0][0]:.3f} {z[0][1]:.3f} {z[0][2]:.3f}")
    print(f"{z[1][0]:.3f} {z[1][1]:.3f} {z[1][2]:.3f}")
    print(f"{z[2][0]:.3f} {z[2][1]:.3f} {z[2][2]:.3f}")
